---
- name: Stop slave
  command: mysql -uroot -p{{ mysql_root_password }} -h {{ mysql_replication_slave }} -e "stop slave;"
#  when: slave != 'None' and slave != {{ master }}
  ignore_errors: yes

- name: show master status
  command: mysql -uroot -p{{ mysql_root_password }} -e "show master status;"

- name: Configure replication slave master in MySQL
  command: mysql -uroot -p{{ mysql_root_password }} -h {{ mysql_replication_slave }} -e "CHANGE MASTER TO MASTER_HOST='{{ mysql_replication_master }}', MASTER_USER='{{ masteruser }}', MASTER_PASSWORD='{{ mysql_root_password }}', MASTER_LOG_FILE='{{ masterlogfile }}', MASTER_LOG_POS={{ masterlogpos }};"
#  when: slave != 'None' and slave != {{ master }}

- name: Start MySQL slave
  command: mysql -uroot -p{{ mysql_root_password }} -h {{ mysql_replication_slave }} -e "start slave;"
#  when: slave != 'None' and slave != {{ master }}
