---
- name: install tools
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - rsyslog
  tags:
    - rsyslog

- name: Setup rsyslog template
  copy:
    dest: /etc/rsyslog.conf
    src: rsyslog.conf
    mode: 0600
    owner: root
    group: root
  notify: restart_rsyslog

- name: add export logs to rsyslogserver
  lineinfile:
    path: /etc/rsyslog.conf
    line: '*.* @@log.sys.toolsams1.cloudsys.tmcs:514'
  tags:
    - rsyslog

- name: restart rsyslog
  service:
    name: rsyslog
    enabled: yes
    state: restarted
  tags:
    - rsyslog
