---
- name: allow root Auth
  replace: 
    dest: /etc/ssh/sshd_config
    regexp: '#PermitRootLogin yes' 
    replace: 'PermitRootLogin yes' 
  tags:
    - auth

- name: allow root pwd Auth
  replace:
    dest: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
  tags:
    - auth

- name: restart sshd
  service:
    name: sshd
    state: restarted
  tags:
    - auth
