---
- name: Add Ticketmaster Repo
  yum_repository:
    name: Ticketmaster
    description: Ticketmaster Repo
    baseurl: http://repo1.int.toolsams1.cloudsys.tmcs/CentOS/ticketmaster/
  tags:
    - akfgen

- name: Install AKFGEN
  yum:
    name: akfgen.x86_64
    validate_certs: false
    disable_gpg_check: true
    state: present
  tags:
    - akfgen

- name: Add akfgen configuration file
  copy:
    dest: /etc/akfgen.yml
    src: akfgen.yml
    mode: 0600
    owner: root
    group: root
  tags:
    - akfgen

- name: Add akfgen systemd service
  copy:
    dest: /etc/systemd/system/akfgen.service
    src: akfgen.service
    mode: 0777
    owner: root
    group: root
  tags:
    - akfgen

- name: Add akfgen systemd timer
  copy:
    dest: /etc/systemd/system/akfgen.timer
    src: akfgen.timer
    mode: 0777
    owner: root
    group: root
  tags:
    - akfgen

- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: true
  tags:
    - akfgen

- name: enable service akfgen and ensure it is not masked
  systemd:
    name: akfgen.service
    enabled: true
    masked: false
  tags:
    - akfgen

- name: enable service akfgen and ensure it is not masked
  systemd:
    name: akfgen.timer
    enabled: true
    masked: false
  tags:
    - akfgen

- name: Make sure a service is running
  systemd:
    state: started
    name: akfgen.timer
  tags:
    - akfgen
