---
# Disable Firewalld
- name: firewalld disable
  service:
    name: firewalld
    enabled: no
    state: stopped
  tags:
    - firewall

#yum install firewalld
#systemctl enable firewalld
#systemctl start firewalld
#firewall-cmd --permanent --list-all
#firewall-cmd --permanent --zone=public --add-port=2234/tcp
#firewall-cmd --zone=public --permanent --add-service=http
