---
- name: Ensure hostname set
  hostname: name={{ inventory_hostname }}
  when: not inventory_hostname|match('(\d{1,3}\.){3}\d{1,3}')
  tags:
    - hostname

#- name: set hostname
#  hostname: name={{ hostname.replace('*', ansible_all_ipv4_addresses[0].split('.')[3]) }}

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}.+$"
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}"
  tags:
    - hostname


#- name: Keep temporary old hostname in /etc/hosts
#  lineinfile:
#    dest=/etc/hosts
#    regexp="^127\.0\.1\.1(.*)"
#    line="127.0.1.1{{'\t'}}{% if hostname_name != hostname_fqdn %}{{ hostname_fqdn }}{{'\t'}}{% endif %}{{ hostname_name }}\1"
#    state=present
#    backup=yes
#    backrefs=yes
#  tags:
#    - hostname

#- name: testttt
#  debug: var=hostvars[inventory_hostname]['ansible_default_ipv4']['address']

- name: install tools
  yum:
    name: "{{ item }}"
  with_items:
    - bind-utils
  tags:
    - hostname

#- name: Determine IP
#  lineinfile:
#    dest=/tmp/ip
#    line="{{ ansible_eth0.ipv4.address }}"
#    state=present
#    create=yes

#- name: get FQDN from dns server
#  command: nslookup $(cat /tmp/ip) | sed -n 's/.*arpa.*name = \(.*\)/\1/p' > /tmp/hostname

#- name: Set static hostname
#  command: hostnamectl set-hostname --static $(cat /tmp/hostname)

#- name: Set hostname
#  hostname: name={{ hostname_name }}
#  when: hostname_name is defined
#  tags:
#    - hostname

#- name: Update /etc/hosts
#  lineinfile:
#    dest=/etc/hosts
#    regexp="^127\.0\.1\.1"
#    line="127.0.1.1{{'\t'}}{% if hostname_name != hostname_fqdn %}{{ hostname_fqdn }}{{'\t'}}{% endif %}{{ hostname_name }}"
#    state=present
#  tags:
#    - hostname

#  template:
#    src: ../../../templates/ifcfg-{{ item }}
#    dest: /etc/sysconfig/network-scripts/ifcfg-{{ item }}
#  with_items:
#   - "{{ ansible_interfaces | map('replace', '-','_') | list }}"
#   - {{ ansible_interfaces }}
#- copy: src=/repo/{{ ansible_default_ipv4.address }}/file.conf dest=/etc/file.conf owner=foo group=foo mode=0644
