---
- name: CloudStack server installation
  hosts: first-controller
  gather_facts: true
  become: true
  become_user: root
  vars_files:
    - vars/main.yml

  roles:
  - role: updates
    tags: [updates]
  - role: rpm
    tags: [rpm]
  - role: mysql-config-first-one
    tags: [mysql-config-first-one]
  - role: mysql-restart
    tags: [mysql-restart]
  - role: mysql-root-password
    tags: [mysql-root-password]
  - role: mysql-user-replication-create-one
    tags: [mysql-user-replication-create-one]
  - role: run-first-cs-one
    tags: [run-first-cs-one]
## (need check this parts)
  - role: cs-db-properties
    tags: [cs-db-properties]
#  - role: cs-rules
#    tags: [cs-rules]
  - role: ldap-config-cert
    tags: [ldap-config-cert]
  - role: disable-sni
    tags: [disable-sni]
  - role: extension-rpm
    tags: [extension-rpm]
  - role: cloudmonkey
    tags: [cloudmonkey]
