---
- name: Export
  shell: "export AWS creds for r53"

- name: Export AWS_ACCESS_KEY_ID
  shell: "export AWS_ACCESS_KEY_ID={{ LetsEncryptCreds }}"

- name: clone acme file
  shell: git clone https://github.com/Neilpang/acme.sh.git
  ignore_errors: true

- name: Export
  shell: "export AWS_SECRET_ACCESS_KEY={{ LetsEncryptCreds }}"

- name: Generate certs valid for all public IPs for the zone
  shell: "/root/.acme.sh/acme.sh  --issue --dns dns_aws -d {{ CSDOM }} -d '*.svm.{{ CSDOM }}'"
  ignore_errors: true      #check with real domain

- name: Concatenate for HA proxy, cer
  shell: "cat /root/.acme.sh/{{ CSDOM }}/{{ CSDOM }}.crt > {{ CSDOM }}.pem"
  ignore_errors: true     #check with real domain

- name: Concatenate for HA proxy, key
  shell: "cat /root/.acme.sh/{{ CSDOM }}/{{ CSDOM }}.key >> {{ CSDOM }}.pem"
  ignore_errors: true     #check with real domain

- name: Copy cert to the local folder
  shell: "cp {{ CSDOM }}.pem /etc/haproxy/"
  ignore_errors: true

- name: Copy cert to the second controller
  shell: "scp {{ CSDOM }}.pem {{ mysql_replication_slave }}:/etc/haproxy/"
  ignore_errors: true
